### PR TITLE
Update for data-cy-debug="tableRow"

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
Ik heb dit op mijn laptop getest. Het gaat in CI/CD pas slagen als er een nieuwe ladybug-frontend release in het FF! zit.

**Review by MarkvdVorst — CHANGES_REQUESTED** [review]
Instead of using the data-cy tag to get the tablerow, it's better to use the getTableRows command now. This should be applied everywhere where .find or .get is used to get the table rows

**Comment by mhdirkse** [comment]
There is no getTableRows command yet. I think it is not a good idea to create it. Using a get or find to query the data-cy tag is only a single statement that is easy to understand. The code does not become easier to understand with the new function, because then you have to read the function body if you want to understand what you are doing.

We already use data-cy* attributes to make the test independent of implementation details.

I also wonder whether debugging will become easier when the test fails. Cypress does not give correct line numbers when showing an error. Can you live with it when I merge this PR?

**Comment by MarkvdVorst** [comment]
Please fix the failing tests first and then I'll take a look at it again. Just hit the "re-request review" button on top right and I'll see it pop up in my notifications.

**Comment by mhdirkse** [comment]
The fix is that the FF! should have the new data-cy* tags. I am working on that.

**Comment by mhdirkse** [comment]
FF! PR https://github.com/frankframework/frankframework/pull/7264.

**Pull request merged**
